n=input('Digite algo: ')
print('O tipo primitivo desse valor é',type(n))
print('Só tem espaços?',n.isspace())
print('contém apenas números?',n.isnumeric())
print('contém apenas letras?',n.isalpha())
print('é alphanumérico?',n.isalnum())
print('é decimal?',n.isdecimal())
print('contém apenas letras maiúsculas?',n.isupper())
print('contém apenas letras minúsculas?',n.islower())
print('está capitalizada?',n.istitle())
